# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:android)

platform :android do
  desc "Deploy marketing"
  lane :deploy_marketing do
    begin
      upload_to_play_store(
        metadata_path: "./metadata",
        skip_upload_metadata: false,
        skip_upload_images: false,
        skip_upload_screenshots: false,
        skip_upload_changelogs: true,
      )
    end
  end
end

platform :android do
  desc "Deploy Changelogs"
  lane :deploy_changelogs do
    begin
      upload_to_play_store(
        metadata_path: "./metadata",
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        skip_upload_changelogs: false,
      )
    end
  end
end
