force true # To go into non interactive mode
app_identifier "org.openfoodfacts.app"
username ENV["APPLE_ID"]
app_icon "./fastlane/ios/fastlane/metadata/Icon-App-iTunes.png"
screenshots_path "./fastlane/ios/fastlane/screenshots"
metadata_path "./fastlane/ios/fastlane/metadata"

#languages	Metadata: List of languages to activate

