default_platform(:ios)

#before_all do
#  xcversion(version: "~> 13.3.1")
#end

platform :ios do
    desc "Precheck metadata for Apple compliance"
    lane :run_precheck do
      precheck
    end
  
    desc "Push only description and meta info"
    lane :metadata do
      
        api_key = app_store_connect_api_key(
          key_id: ENV["SPACESHIP_CONNECT_API_KEY_ID"],
          issuer_id: ENV["SPACESHIP_CONNECT_API_ISSUER_ID"],
          key_filepath: ENV["SPACESHIP_CONNECT_API_KEY_FILEPATH"]
        )
        deliver(
        api_key: api_key,
        skip_screenshots: false,
        skip_metadata: false,
        force: true, # To go into non interactive mode
        precheck_include_in_app_purchases: false
        )
    end

  desc "Sending metadata for Smoothie to TestFlight"
  lane :beta do

    APP_IDENTIFIER = "org.openfoodfacts.app"
    
    puts "Sending metadata for identifier #{APP_IDENTIFIER}"

    sync_code_signing(type: "appstore", readonly: is_ci, clone_branch_directly: false)
    update_code_signing_settings(
      path: "Runner.xcodeproj",
      use_automatic_signing: false,
      build_configurations: "Release",
      code_sign_identity: 'iPhone Distribution',
      profile_name: 'match AppStore org.openfoodfacts.app',
      targets: ["Runner"]
    )
  
    update_project_team(
      path: "Runner.xcodeproj",
      teamid: "ZC9CYWD334"
    )
  
    # Upload to TestFlight
    pilot(
      app_identifier: APP_IDENTIFIER,
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      #ipa: "./Runner.ipa"
      #skip_screenshots: false,
      #skip_metadata: false
    )
  end

  desc "Sending only Changelogs to TestFlight"
  lane :upload_changelogs do

    APP_IDENTIFIER = "org.openfoodfacts.app"
    
    puts "Sending changelogs for identifier #{APP_IDENTIFIER}"

    sync_code_signing(type: "appstore", readonly: is_ci, clone_branch_directly: false)
    update_code_signing_settings(
      path: "Runner.xcodeproj",
      use_automatic_signing: false,
      build_configurations: "Release",
      code_sign_identity: 'iPhone Distribution',
      profile_name: 'match AppStore org.openfoodfacts.app',
      targets: ["Runner"]
    )
  
    update_project_team(
      path: "Runner.xcodeproj",
      teamid: "ZC9CYWD334"
    )
  
    # Upload changelog to TestFlight
    pilot(
      app_identifier: APP_IDENTIFIER,
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      skip_screenshots: true,
      skip_metadata: true
    )
  end

  lane :setVersion do
    begin

        new_version_name = ENV["VERSION_NAME"]
        new_version_name = new_version_name.to_s
        new_version_name = new_version_name[8..-1]
        puts new_version_name

        api_key = app_store_connect_api_key(
          key_id: ENV["SPACESHIP_CONNECT_API_KEY_ID"],
          issuer_id: ENV["SPACESHIP_CONNECT_API_ISSUER_ID"],
          key_filepath: ENV["SPACESHIP_CONNECT_API_KEY_FILEPATH"]
        )

        old_version_code = app_store_build_number(
          live: false,
          api_key: api_key,
          app_identifier: "org.openfoodfacts.app",
          initial_build_number: "0",
          version: new_version_name
        )
        new_version_code = old_version_code.to_i + 1

        puts "old_version_code: " + old_version_code.to_s
        puts "new_version_code: " + new_version_code.to_s

        flutter_set_version(
          path_to_yaml: "../pubspec.yaml",
          version_name: new_version_name,
          version_code:  new_version_code.to_s,
        )
    end
end



end
