name: Upload Metadata for iOS using Fastlane
on:
  push:
    branches:
      - 'upload-to-appstore'

jobs:
  testflight-release:
    name: Deploy marketing assets to the Apple App Store
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.4

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Version
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0.2
      - name: Bundle install
        run: cd ./fastlane/ios/fastlane && gem install bundler:1.17.3 && bundle install && pwd && ls

      - name: Decrypt AuthKey file
        run: pwd && ls && cd ./fastlane/ios/fastlane/envfiles && ./decrypt_secrets.sh && ls && pwd
        env:
          AUTH_KEY_FILE_DECRYPTKEY: ${{ secrets.AUTH_KEY_FILE_DECRYPTKEY }}
          
      - name: Publish marketing assets
        run: cd ./fastlane/ios/fastlane && pwd && ls && bundle exec fastlane metadata
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          PILOT_APPLE_ID: ${{ secrets.PILOT_APPLE_ID }}
          SPACESHIP_CONNECT_API_ISSUER_ID: ${{ secrets.SPACESHIP_CONNECT_API_ISSUER_ID }}
          SPACESHIP_CONNECT_API_KEY_ID: ${{ secrets.SPACESHIP_CONNECT_API_KEY_ID }}
          SPACESHIP_CONNECT_API_KEY_FILEPATH: ./fastlane/envfiles/AuthKey_KDAUTTM76R.p8
          CI_RELEASE: true

